# HyperGraph Web UI SSH Tunnel Script (Windows PowerShell)
# Auto-generated by start_remote_ui.py
#
# Usage: .\connect_to_hypergraph_ui.ps1 [-ServerHost "hostname"]
# Edit the configuration below for other settings.

param(
    [string]$ServerHost = "nsf-gpu.main.ad.rit.edu"
)

# ============ CONFIGURATION - Edit these for your environment ============
$Username = "brg2890"
$RemotePort = 5000
$LocalPort = 5000
# ========================================================================

Write-Host "[CONNECT] Connecting to HyperGraph Web UI..." -ForegroundColor Green
Write-Host "   Server: ${Username}@${ServerHost}" -ForegroundColor Yellow
Write-Host "   Local:  http://localhost:$LocalPort (will auto-adjust if busy)" -ForegroundColor Yellow
Write-Host "   Remote: port $RemotePort" -ForegroundColor Yellow
Write-Host ""

# Kill any existing SSH processes on this port
Write-Host "[CHECK] Checking for existing SSH tunnels..." -ForegroundColor Blue
Get-Process ssh -ErrorAction SilentlyContinue | Where-Object {
    $_.CommandLine -like "*-L*${LocalPort}:localhost:${RemotePort}*"
} | Stop-Process -Force -ErrorAction SilentlyContinue

# Function to test if port is available
function Test-Port {
    param([int]$Port)
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    } catch {
        return $false
    }
}

# Find available port starting from requested port
$originalPort = $LocalPort
$testPort = $originalPort
$maxAttempts = 50

Write-Host "[PORT] Checking port availability..." -ForegroundColor Blue
while (-not (Test-Port $testPort) -and ($testPort - $originalPort) -lt $maxAttempts) {
    $testPort++
}

if (($testPort - $originalPort) -ge $maxAttempts) {
    Write-Host "[ERROR] Could not find available port in range $originalPort-$($originalPort + $maxAttempts)" -ForegroundColor Red
    Write-Host "Try closing other applications or restarting your computer" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

if ($testPort -ne $originalPort) {
    Write-Host "[INFO] Port $originalPort is busy, using port $testPort instead" -ForegroundColor Yellow
}

Write-Host "[START] Starting SSH tunnel with auto-restart..." -ForegroundColor Green
Write-Host "   Keep this PowerShell window open while using the web UI" -ForegroundColor Cyan
Write-Host "   Press Ctrl+C to close the tunnel" -ForegroundColor Cyan
Write-Host "   Access the UI at: http://localhost:$testPort" -ForegroundColor Magenta
Write-Host ""

# Create SSH tunnel with auto-restart and compression
while ($true) {
    try {
        ssh -N -C -L "$testPort`:localhost:$RemotePort" `
            -o ServerAliveInterval=60 `
            -o ServerAliveCountMax=3 `
            -o ExitOnForwardFailure=yes `
            -o ConnectTimeout=10 `
            ${Username}@${ServerHost}
    } catch {
        Write-Host "[RETRY] Connection lost. Retrying in 5 seconds..." -ForegroundColor Yellow
        Write-Host "   Press Ctrl+C to stop" -ForegroundColor Yellow
        Start-Sleep 5
    }
}
