#!/bin/bash
# HyperGraph Web UI SSH Tunnel Script (Linux/macOS)
# Auto-generated by start_remote_ui.py

echo "🔗 Connecting to HyperGraph Web UI..."
echo "   Server: brg2890@nsf-gpu.main.ad.rit.edu"
echo "   Local:  http://localhost:5000"
echo "   Remote: port 5000"
echo ""

# Kill any existing tunnels on this port
pkill -f "ssh.*-L.*5000:localhost:5000" 2>/dev/null

echo "🚀 Starting SSH tunnel..."
echo "   Keep this terminal open while using the web UI"
echo "   Press Ctrl+C to close the tunnel"
echo ""

# Create SSH tunnel with auto-restart and compression
while true; do
    ssh -N -C -L 5000:localhost:5000 \
        -o ServerAliveInterval=60 \
        -o ServerAliveCountMax=3 \
        -o ExitOnForwardFailure=yes \
        -o ConnectTimeout=10 \
        brg2890@nsf-gpu.main.ad.rit.edu
    
    echo "⚠️  Connection lost. Retrying in 5 seconds..."
    echo "   Press Ctrl+C to stop"
    sleep 5
done
