@echo off
REM HyperGraph Web UI SSH Tunnel Script (Windows Batch)
REM Auto-generated by start_remote_ui.py

echo [CONNECT] Connecting to HyperGraph Web UI...
echo    Server: brg2890@nsf-gpu.main.ad.rit.edu
echo    Local:  http://localhost:5000
echo    Remote: port 5000
echo.

echo [START] Starting SSH tunnel with auto-restart...
echo    Keep this command prompt open while using the web UI
echo    Press Ctrl+C to close the tunnel
echo.

:restart
ssh -N -C -L 5000:localhost:5000 ^
    -o ServerAliveInterval=60 ^
    -o ServerAliveCountMax=3 ^
    -o ExitOnForwardFailure=yes ^
    -o ConnectTimeout=10 ^
    brg2890@nsf-gpu.main.ad.rit.edu

echo [RETRY] Connection lost. Retrying in 5 seconds...
echo    Press Ctrl+C to stop
timeout /t 5 /nobreak >nul
goto restart
