#!/usr/bin/env python3
"""
Complete Remote UI Setup for HyperGraph

This script provides a complete solution for starting the HyperGraph Web UI
with automated SSH tunnel setup. It handles dependency installation,
tunnel script generation, and provides all necessary instructions.

Author: Quanty 7
"""

import os
import sys
import subprocess
import socket
import argparse
from pathlib import Path

def check_dependencies():
    """Check if required dependencies are installed."""
    # Map package names to import names
    required_packages = {
        'flask': 'flask',
        'psutil': 'psutil', 
        'pyyaml': 'yaml'
    }
    missing_packages = []
    
    for package_name, import_name in required_packages.items():
        try:
            __import__(import_name)
        except ImportError:
            missing_packages.append(package_name)
    
    return missing_packages

def install_dependencies(packages):
    """Install missing dependencies."""
    print(f"📦 Installing missing packages: {', '.join(packages)}")
    try:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install'] + packages)
        print("✅ Dependencies installed successfully")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to install dependencies")
        return False

def get_server_info():
    """Get server connection information."""
    try:
        hostname = socket.gethostname()
        # Get local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
        s.close()
        
        return {
            'hostname': hostname,
            'ip': local_ip,
            'server_host': hostname if 'rit.edu' in hostname or 'nsf-gpu' in hostname else local_ip
        }
    except Exception as e:
        print(f"Error getting server info: {e}")
        return None

def create_tunnel_script(server_info, username, local_port=5000, remote_port=5000):
    """Create SSH tunnel scripts for all platforms."""
    server_host = server_info['server_host']
    
    # Create bash script for Linux/macOS
    bash_script_content = f'''#!/bin/bash
# HyperGraph Web UI SSH Tunnel Script (Linux/macOS)
# Auto-generated by start_remote_ui.py

echo "🔗 Connecting to HyperGraph Web UI..."
echo "   Server: {username}@{server_host}"
echo "   Local:  http://localhost:{local_port}"
echo "   Remote: port {remote_port}"
echo ""

# Kill any existing tunnels on this port
pkill -f "ssh.*-L.*{local_port}:localhost:{remote_port}" 2>/dev/null

echo "🚀 Starting SSH tunnel..."
echo "   Keep this terminal open while using the web UI"
echo "   Press Ctrl+C to close the tunnel"
echo ""

# Create SSH tunnel with auto-restart and compression
while true; do
    ssh -N -C -L {local_port}:localhost:{remote_port} \\
        -o ServerAliveInterval=60 \\
        -o ServerAliveCountMax=3 \\
        -o ExitOnForwardFailure=yes \\
        -o ConnectTimeout=10 \\
        {username}@{server_host}
    
    echo "⚠️  Connection lost. Retrying in 5 seconds..."
    echo "   Press Ctrl+C to stop"
    sleep 5
done
'''
    
    # Create PowerShell script for Windows
    powershell_script_content = f'''# HyperGraph Web UI SSH Tunnel Script (Windows PowerShell)
# Auto-generated by start_remote_ui.py

Write-Host "[CONNECT] Connecting to HyperGraph Web UI..." -ForegroundColor Green
Write-Host "   Server: {username}@{server_host}" -ForegroundColor Yellow
Write-Host "   Local:  http://localhost:{local_port} (will auto-adjust if busy)" -ForegroundColor Yellow
Write-Host "   Remote: port {remote_port}" -ForegroundColor Yellow
Write-Host ""

# Kill any existing SSH processes on this port
Write-Host "[CHECK] Checking for existing SSH tunnels..." -ForegroundColor Blue
Get-Process ssh -ErrorAction SilentlyContinue | Where-Object {{
    $_.CommandLine -like "*-L*{local_port}:localhost:{remote_port}*"
}} | Stop-Process -Force -ErrorAction SilentlyContinue

# Function to test if port is available
function Test-Port {{
    param([int]$Port)
    try {{
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    }} catch {{
        return $false
    }}
}}

# Find available port starting from requested port
$originalPort = {local_port}
$testPort = $originalPort
$maxAttempts = 50

Write-Host "[PORT] Checking port availability..." -ForegroundColor Blue
while (-not (Test-Port $testPort) -and ($testPort - $originalPort) -lt $maxAttempts) {{
    $testPort++
}}

if (($testPort - $originalPort) -ge $maxAttempts) {{
    Write-Host "[ERROR] Could not find available port in range $originalPort-$($originalPort + $maxAttempts)" -ForegroundColor Red
    Write-Host "Try closing other applications or restarting your computer" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}}

if ($testPort -ne $originalPort) {{
    Write-Host "[INFO] Port $originalPort is busy, using port $testPort instead" -ForegroundColor Yellow
}}

Write-Host "[START] Starting SSH tunnel with auto-restart..." -ForegroundColor Green
Write-Host "   Keep this PowerShell window open while using the web UI" -ForegroundColor Cyan
Write-Host "   Press Ctrl+C to close the tunnel" -ForegroundColor Cyan
Write-Host "   Access the UI at: http://localhost:$testPort" -ForegroundColor Magenta
Write-Host ""

# Create SSH tunnel with auto-restart and compression
while ($true) {{
    try {{
        ssh -N -C -L "$testPort`:localhost:{remote_port}" `
            -o ServerAliveInterval=60 `
            -o ServerAliveCountMax=3 `
            -o ExitOnForwardFailure=yes `
            -o ConnectTimeout=10 `
            {username}@{server_host}
    }} catch {{
        Write-Host "[RETRY] Connection lost. Retrying in 5 seconds..." -ForegroundColor Yellow
        Write-Host "   Press Ctrl+C to stop" -ForegroundColor Yellow
        Start-Sleep 5
    }}
}}
'''
    
    # Create batch file for Windows (fallback)
    batch_script_content = f'''@echo off
REM HyperGraph Web UI SSH Tunnel Script (Windows Batch)
REM Auto-generated by start_remote_ui.py

echo [CONNECT] Connecting to HyperGraph Web UI...
echo    Server: {username}@{server_host}
echo    Local:  http://localhost:{local_port}
echo    Remote: port {remote_port}
echo.

echo [START] Starting SSH tunnel with auto-restart...
echo    Keep this command prompt open while using the web UI
echo    Press Ctrl+C to close the tunnel
echo.

:restart
ssh -N -C -L {local_port}:localhost:{remote_port} ^
    -o ServerAliveInterval=60 ^
    -o ServerAliveCountMax=3 ^
    -o ExitOnForwardFailure=yes ^
    -o ConnectTimeout=10 ^
    {username}@{server_host}

echo [RETRY] Connection lost. Retrying in 5 seconds...
echo    Press Ctrl+C to stop
timeout /t 5 /nobreak >nul
goto restart
'''
    
    # Save all scripts
    bash_script_path = Path("connect_to_hypergraph_ui.sh")
    powershell_script_path = Path("connect_to_hypergraph_ui.ps1")
    batch_script_path = Path("connect_to_hypergraph_ui.bat")
    
    bash_script_path.write_text(bash_script_content)
    bash_script_path.chmod(0o755)
    
    powershell_script_path.write_text(powershell_script_content, encoding='utf-8')
    batch_script_path.write_text(batch_script_content, encoding='utf-8')
    
    return {
        'bash': bash_script_path,
        'powershell': powershell_script_path,
        'batch': batch_script_path
    }

def create_oneliner_script(server_info, username, local_port=5000, remote_port=5000):
    """Create one-liner scripts that start both tunnel and UI."""
    server_host = server_info['server_host']
    current_dir = os.getcwd()
    
    # Create bash script for Linux/macOS
    bash_script_content = f'''#!/bin/bash
# HyperGraph Web UI One-Liner Connection Script (Linux/macOS)
# Auto-generated by start_remote_ui.py

echo "🚀 Starting HyperGraph Web UI with tunnel..."
echo "   This will start the web UI on the server and tunnel to your machine"
echo "   Access at: http://localhost:{local_port}"
echo ""

# Kill any existing tunnels on this port
pkill -f "ssh.*-L.*{local_port}:localhost:{remote_port}" 2>/dev/null

# Start tunnel and UI in one command
ssh -L {local_port}:localhost:{remote_port} {username}@{server_host} \\
    "cd {current_dir} && export PATH=/home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin:$PATH && /home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin/python start_ui.py"
'''
    
    # Create PowerShell script for Windows
    powershell_script_content = f'''# HyperGraph Web UI One-Liner Connection Script (Windows PowerShell)
# Auto-generated by start_remote_ui.py

Write-Host "[START] Starting HyperGraph Web UI with tunnel..." -ForegroundColor Green
Write-Host "   This will start the web UI on the server and tunnel to your machine" -ForegroundColor Yellow
Write-Host "   Initial port: {local_port} (will auto-adjust if busy)" -ForegroundColor Magenta
Write-Host ""

# Kill any existing SSH processes on this port
Write-Host "[CHECK] Checking for existing SSH tunnels..." -ForegroundColor Blue
Get-Process ssh -ErrorAction SilentlyContinue | Where-Object {{
    $_.CommandLine -like "*-L*{local_port}:localhost:{remote_port}*"
}} | Stop-Process -Force -ErrorAction SilentlyContinue

# Function to test if port is available
function Test-Port {{
    param([int]$Port)
    try {{
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    }} catch {{
        return $false
    }}
}}

# Find available port starting from requested port
$originalPort = {local_port}
$testPort = $originalPort
$maxAttempts = 50

Write-Host "[PORT] Checking port availability..." -ForegroundColor Blue
while (-not (Test-Port $testPort) -and ($testPort - $originalPort) -lt $maxAttempts) {{
    $testPort++
}}

if (($testPort - $originalPort) -ge $maxAttempts) {{
    Write-Host "[ERROR] Could not find available port in range $originalPort-$($originalPort + $maxAttempts)" -ForegroundColor Red
    Write-Host "Try closing other applications or restarting your computer" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}}

if ($testPort -ne $originalPort) {{
    Write-Host "[INFO] Port $originalPort is busy, using port $testPort instead" -ForegroundColor Yellow
}}

Write-Host "[INFO] Access the UI at: http://localhost:$testPort" -ForegroundColor Magenta

# Create the remote command with environment setup
$remoteCommand = "cd {current_dir} && export PATH=/home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin:$PATH && /home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin/python start_ui.py"

# Start tunnel and UI in one command
Write-Host "[CONNECT] Connecting and starting UI..." -ForegroundColor Green
ssh -L "$testPort`:localhost:{remote_port}" {username}@{server_host} $remoteCommand
'''
    
    # Create batch file for Windows (fallback)
    batch_script_content = f'''@echo off
REM HyperGraph Web UI One-Liner Connection Script (Windows Batch)
REM Auto-generated by start_remote_ui.py

echo [START] Starting HyperGraph Web UI with tunnel...
echo    This will start the web UI on the server and tunnel to your machine
echo    Access at: http://localhost:{local_port}
echo.

REM Start tunnel and UI in one command
echo [CONNECT] Connecting and starting UI...
ssh -L {local_port}:localhost:{remote_port} {username}@{server_host} ^
    "cd {current_dir} && export PATH=/home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin:$PATH && /home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin/python start_ui.py"
'''
    
    # Save all scripts
    bash_script_path = Path("start_hypergraph_ui_remote.sh")
    powershell_script_path = Path("start_hypergraph_ui_remote.ps1")
    batch_script_path = Path("start_hypergraph_ui_remote.bat")
    
    bash_script_path.write_text(bash_script_content)
    bash_script_path.chmod(0o755)
    
    powershell_script_path.write_text(powershell_script_content, encoding='utf-8')
    batch_script_path.write_text(batch_script_content, encoding='utf-8')
    
    return {
        'bash': bash_script_path,
        'powershell': powershell_script_path,
        'batch': batch_script_path
    }

def main():
    parser = argparse.ArgumentParser(description="Complete HyperGraph Remote UI Setup")
    parser.add_argument('--username', type=str, help='SSH username for server connection')
    parser.add_argument('--local-port', type=int, default=5000, help='Local port for tunnel')
    parser.add_argument('--remote-port', type=int, default=5000, help='Remote port for web UI')
    parser.add_argument('--start-ui', action='store_true', help='Start the web UI immediately')
    parser.add_argument('--auto-install', action='store_true', help='Automatically install missing dependencies')
    
    args = parser.parse_args()
    
    print("🧠 HyperGraph Remote UI Setup")
    print("=" * 50)
    
    # Check if we're in the right directory
    if not os.path.exists('test_hierarchical.py'):
        print("❌ Error: Please run this script from the HyperGraph project root directory")
        print("   (where test_hierarchical.py is located)")
        sys.exit(1)
    
    # Check dependencies
    print("🔍 Checking dependencies...")
    missing_deps = check_dependencies()
    
    if missing_deps:
        if args.auto_install:
            if not install_dependencies(missing_deps):
                sys.exit(1)
        else:
            print(f"❌ Missing dependencies: {', '.join(missing_deps)}")
            print("   Install with: pip install flask psutil pyyaml")
            print("   Or use --auto-install flag")
            sys.exit(1)
    else:
        print("✅ Dependencies OK")
    
    # Get server information
    print("🌐 Detecting server information...")
    server_info = get_server_info()
    if not server_info:
        print("❌ Could not detect server information")
        sys.exit(1)
    
    print(f"✅ Server detected: {server_info['hostname']} ({server_info['ip']})")
    
    # Get username if not provided
    if not args.username:
        print("\n👤 SSH Username Setup:")
        args.username = input("Enter your SSH username for this server: ").strip()
        if not args.username:
            print("❌ Username is required for SSH tunnel setup")
            sys.exit(1)
    
    print(f"✅ Using username: {args.username}")
    
    # Create necessary directories
    print("📁 Creating directories...")
    dirs_to_create = [
        'web_ui/configs',
        'web_ui/runs', 
        'web_ui/config_templates',
        'web_ui/static/css',
        'web_ui/static/js'
    ]
    
    for directory in dirs_to_create:
        os.makedirs(directory, exist_ok=True)
    
    print("✅ Directories created")
    
    # Create connection scripts
    print("📝 Creating connection scripts...")
    
    # Basic tunnel scripts
    tunnel_scripts = create_tunnel_script(server_info, args.username, args.local_port, args.remote_port)
    print(f"✅ Created tunnel scripts:")
    print(f"   🐧 {tunnel_scripts['bash']}")
    print(f"   🪟 {tunnel_scripts['powershell']}")
    print(f"   🪟 {tunnel_scripts['batch']}")
    
    # One-liner scripts
    oneliner_scripts = create_oneliner_script(server_info, args.username, args.local_port, args.remote_port)
    print(f"✅ Created one-liner scripts:")
    print(f"   🐧 {oneliner_scripts['bash']}")
    print(f"   🪟 {oneliner_scripts['powershell']}")
    print(f"   🪟 {oneliner_scripts['batch']}")
    
    # Display setup instructions
    print("\n" + "=" * 60)
    print("🎉 SETUP COMPLETE!")
    print("=" * 60)
    
    print(f"\n📋 Connection Scripts Created:")
    print(f"   Manual Tunnel (start UI separately):")
    print(f"     🐧 Linux/macOS: {tunnel_scripts['bash'].name}")
    print(f"     🪟 Windows PS:  {tunnel_scripts['powershell'].name}")
    print(f"     🪟 Windows CMD: {tunnel_scripts['batch'].name}")
    print(f"   Automatic (tunnel + UI startup):")
    print(f"     🐧 Linux/macOS: {oneliner_scripts['bash'].name}")
    print(f"     🪟 Windows PS:  {oneliner_scripts['powershell'].name}")
    print(f"     🪟 Windows CMD: {oneliner_scripts['batch'].name}")
    
    print(f"\n💻 Usage Instructions:")
    print(f"   🐧 Linux/macOS:")
    print(f"      chmod +x *.sh")
    print(f"      ./{tunnel_scripts['bash'].name}  (manual)")
    print(f"      ./{oneliner_scripts['bash'].name}  (automatic)")
    print(f"   🪟 Windows PowerShell:")
    print(f"      Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser")
    print(f"      .\\{tunnel_scripts['powershell'].name}  (manual)")
    print(f"      .\\{oneliner_scripts['powershell'].name}  (automatic)")
    print(f"   🪟 Windows Command Prompt:")
    print(f"      .\\{tunnel_scripts['batch'].name}  (manual)")
    print(f"      .\\{oneliner_scripts['batch'].name}  (automatic)")
    
    print(f"\n🌐 Access the Web UI at:")
    print(f"   http://localhost:{args.local_port}")
    
    print(f"\n📖 Manual Commands:")
    print(f"   SSH Tunnel: ssh -L {args.local_port}:localhost:{args.remote_port} {args.username}@{server_info['server_host']}")
    print(f"   Start UI:   python start_ui.py")
    
    print(f"\n🔒 Security:")
    print(f"   • All traffic is encrypted through SSH tunnel")
    print(f"   • Web UI is only accessible through the tunnel")
    print(f"   • Close tunnel when finished to free up ports")
    
    # Optionally start the UI
    if args.start_ui:
        print(f"\n🚀 Starting Web UI on port {args.remote_port}...")
        print("   Set up your SSH tunnel from your local machine to connect")
        try:
            os.chdir('web_ui')
            os.system('python app.py')
        except KeyboardInterrupt:
            print("\n👋 Web UI stopped")
    else:
        print(f"\n💡 Next Steps:")
        print(f"   1. Copy a connection script to your local machine")
        print(f"   2. Run the script to establish tunnel and/or start UI")
        print(f"   3. Access http://localhost:{args.local_port} in your browser")
        print(f"   4. Create configurations and start test runs!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1) 