@echo off
REM HyperGraph Web UI One-Liner Connection Script (Windows Batch)
REM Auto-generated by start_remote_ui.py

echo [START] Starting HyperGraph Web UI with tunnel...
echo    This will start the web UI on the server and tunnel to your machine
echo    Access at: http://localhost:5000
echo.

REM Start tunnel and UI in one command
echo [CONNECT] Connecting and starting UI...
ssh -L 5000:localhost:5000 brg2890@nsf-gpu.main.ad.rit.edu ^
    "cd /major/bryce_python_workspace/GraphWork/HyperGraph && export PATH=/home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin:$PATH && /home/brg2890/major/bryce_python_workspace/miniforge3/envs/DeepEARL_new/bin/python start_ui.py"
