# HyperGraph Web UI One-Liner Connection Script (Windows PowerShell)
# Auto-generated by start_remote_ui.py

Write-Host "[START] Starting HyperGraph Web UI with tunnel..." -ForegroundColor Green
Write-Host "   This will start the web UI on the server and tunnel to your machine" -ForegroundColor Yellow
Write-Host "   Initial port: 5000 (will auto-adjust if busy)" -ForegroundColor Magenta
Write-Host ""

# Kill any existing SSH processes on this port
Write-Host "[CHECK] Checking for existing SSH tunnels..." -ForegroundColor Blue
Get-Process ssh -ErrorAction SilentlyContinue | Where-Object {
    $_.CommandLine -like "*-L*5000:localhost:5000*"
} | Stop-Process -Force -ErrorAction SilentlyContinue

# Function to test if port is available
function Test-Port {
    param([int]$Port)
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    } catch {
        return $false
    }
}

# Find available port starting from requested port
$originalPort = 5000
$testPort = $originalPort
$maxAttempts = 50

Write-Host "[PORT] Checking port availability..." -ForegroundColor Blue
while (-not (Test-Port $testPort) -and ($testPort - $originalPort) -lt $maxAttempts) {
    $testPort++
}

if (($testPort - $originalPort) -ge $maxAttempts) {
    Write-Host "[ERROR] Could not find available port in range $originalPort-$($originalPort + $maxAttempts)" -ForegroundColor Red
    Write-Host "Try closing other applications or restarting your computer" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

if ($testPort -ne $originalPort) {
    Write-Host "[INFO] Port $originalPort is busy, using port $testPort instead" -ForegroundColor Yellow
}

Write-Host "[INFO] Access the UI at: http://localhost:$testPort" -ForegroundColor Magenta

# Create the remote command with environment setup
$remoteCommand = "cd /major/bryce_python_workspace/GraphWork/HyperGraph && export PATH=/home/brg2890/major/bryce_python_workspace/miniforge3/envs/Primary/bin:$PATH && /home/brg2890/major/bryce_python_workspace/miniforge3/envs/Primary/bin/python start_ui.py"

# Start tunnel and UI in one command
Write-Host "[CONNECT] Connecting and starting UI..." -ForegroundColor Green
ssh -L "$testPort`:localhost:5000" brg2890@nsf-gpu.main.ad.rit.edu $remoteCommand
