wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725471375.0
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
